### ISSUE TITLE
Java crash

### ISSUE THREAD

**Issue by sorasakaki** [xulihang/BasicCAT-docs#1]
hello,

I am now using this software to help the translation.

but when I start to generate the target file, the java has no response.

Any Idea what is the problem?

I am using win 10 x64 version.

Thanks

regards

Xin

**Comment by xulihang** [comment]
There should be a result report shown in the status bar as below:
![test11](https://user-images.githubusercontent.com/5462205/80283448-31bcae00-874a-11ea-8d2d-d15a934b700b.png)

Target files will be generated in the project/target folder. If there is any error, an error report dialog should appear.

If you still have problems, you can upload a test project here.

**Comment by sorasakaki** [comment]
hello Mr. xulihang

Thank you for your fast reply.

I would like to know how long does it take usually? I start one at 17:30, and now it is 18:10, the software is still not responding .

ps. I am not so familiar with Gitbub. I will try to upload a project here.

**Comment by xulihang** [comment]
>  how long does it take usually?

It depends on files number, size and format. Usually, it takes less than 10 seconds.
You can test a simple txt file first.

**Comment by sorasakaki** [comment]
hello,
I tried another very short word document, it has the same problem.
now I am using java version 8 Update 251.

I tried at least 10 times and just successd one time, I left the software generate the document and cooked the dinner.

**Comment by xulihang** [comment]
A word document is different from a txt file as BasicCAT uses Okapi to convert docx files to xliff files and vice versa. There may be some occasions that the target docx files are not created successfully, but the target xliff files should be created. In that case, try to use rainbow to do the conversion according to the [doc](https://basiccat-docs.readthedocs.io/en/latest/translatingFiles.html#okapi).

It is recommended to use the packaged java 8 (version<8u202) as the latest java by oracle uses a different license and I didn't test these new versions of java.

**Comment by sorasakaki** [comment]
I install Java 8u202 x64, the problem is still there.

In the meanwhile I try to export to review, the software response very fast, but if I want to generate to xlf, then java crash. I also install this software in my laptop, it has the same problem.

I wondered if it is because the orignal document is in German.

**Comment by xulihang** [comment]
Could you send this file to admin@basiccat.org? It may be the xliff filter's problem.

**Comment by xulihang** [comment]
Check out the latest version of BasicCAT: https://www.basiccat.org/download/, which fixes a program not responding problem when xliff files contain `<target />`

**Comment by sorasakaki** [comment]
now it works perfectly!

Thank you for sharing so great software!!
