### ISSUE TITLE
target document

### ISSUE THREAD

**Issue by sorasakaki** [xulihang/BasicCAT-docs#2]
hello Mr. Xu,

sorry to disturb you again, it seems you understand chinese, then i prefer to ask you with chinese.

我把生成的目标文件发给同事看，他用软件打开了生成target的文件。很多不需要翻译的符号显示没翻译。这个情况是正常的嘛？

Xin

**Comment by xulihang** [comment]
你好，
问题描述不是很详细，用什么软件能打开的，不需要翻译的符号是什么，能给个例子吗？

**Comment by sorasakaki** [comment]
我把翻译完的文件生成了xliff文件后发给同事，他同样用basiccat打开。

他看到的文件也是分左右两边的，左边是原文，右边是中文。但是他发现例如k2 X2之类公式的变量，或者1% 5%之类的数学符号在右边都没有显示。
不知道这种情况正常嘛？

**Comment by xulihang** [comment]
读取xliff时会对文本进行分句，如果原文和译文不同，且分出来都是一句时BasicCAT会读取译文，其它情况不会显示译文的。最好还是把BasicCAT的项目发给他打开

xliff中文本的分句应该使用seg-source元素保存，你之前发的xliff文件没有用这一元素，BasicCAT生成的目标文件也就没有保存分句信息。但BasicCAT目前对seg-source的支持也还不是很完善

**Comment by sorasakaki** [comment]
我还有一个问题想请教，这个xliff会像word一样记录作者的信息嘛？

如果我不希望显示作者的信息应该在哪里删除？

**Comment by xulihang** [comment]
xliff不会保存的，tmx会保存

**Comment by xulihang** [comment]
作者信息是在偏好设置-版本控制里自己设的，不设的话会记录为匿名
