### ISSUE TITLE
xlif 格式的问题呢

### ISSUE THREAD

**Issue by sorasakaki** [xulihang/BasicCAT-docs#3]
hello Mr. Xu

我现在又有了一个新的问题，我把翻译好的文件发给公司的同事。

他的反馈如下： 这个xlif文件不是以xml conform的形式创建的，这个我具体也不是很明白。

The XLIF-file was not created in a XML-conform way.

As can be seen from the error in the log file, there is no text between the two XML attributes id and rid.

Something like this cannot be processed by XML parsers. And the other way around, something like that is not produced by any XML writer I know.

**Comment by xulihang** [comment]
我不是很明白这个问题，错误的日志是什么，哪两个XML属性之间没有文字？

不符合XML规范的问题是可能存在的，但我目前还没有发现

**Comment by sorasakaki** [comment]
> 我不是很明白这个问题，错误的日志是什么，哪两个XML属性之间没有文字？
> 
> 不符合XML规范的问题是可能存在的，但我目前还没有发现

我把错误日志发去admin那个邮箱了。

**Comment by xulihang** [comment]
我看了下，可能是标签的问题。要注意译文的标签和原文一致。

现在版本对标签的处理不是很好，看上去会比较乱。

![image](https://user-images.githubusercontent.com/5462205/82979210-14188800-a019-11ea-9848-a90e6f86776e.png)

**Comment by xulihang** [comment]
目前也可以使用okapi处理该xliff，生成供BasicCAT使用的xliff文件，翻译好后再用okapi生成目标文件，这样标签会被简化很多。

**Comment by sorasakaki** [comment]
您好，

就是说目前软件层面没法直接解决这个问题是嘛？

需要用别的软件来处理xliff.


Regards

Xin
已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by xulihang** [comment]
直接用BasicCAT是可以的，但是标签容易出错。用Okapi Rainbow处理下不容易出错

**Comment by sorasakaki** [comment]
还有个问题，就是我们公司产品说明书的文件是用Indesign直接提取出来的。这个xliff要用okapi rainbow再处理一下？还在翻译完还能恢复成能直接导入indesign的文件嘛？

**Comment by xulihang** [comment]
这个xliff应该是lisocon公司自己的工具导出的，导回的时候会检验标签，注意标签正确应该就能导回。我看了下只有最后几个片段有标签需要注意。

使用rainbow生成的xliff会用`<g>`替换`<bpt>`标签，将`<bpt id="11" rid="11">tags</bpt>`转换为`<g id="11"></g>`，在BasicCAT中处理更方便，然后生成译文xliff时也会进行校验。

Rainbow使用方法参见：[面向本地化工程师的开源CAT工具教程](http://blog.xulihang.me/guide-of-open-source-cat-tools-for-localization-engineers/#%E5%A4%84%E7%90%86%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F)

**Comment by sorasakaki** [comment]
hello Mr. Xu,

下面是设计公司发给我们的回复。
我稍微看了下，也就是说Basic CAT目前没法处理文件中的attributes是嘛？

according to the BasicCAT documentation, the inline xliff tags in the target text are treated like normal text (copied / pasted manually). https://docs.basiccat.org/en/latest/translatingFiles.html#xliff
In the translated xliff file are many inline tags where the space between two tag attributes has been omitted.
Xliff files are a special form of XML files that must be "well formed" according to w3c standard.

**Comment by xulihang** [comment]
是当做纯文本处理的，所以翻译时要注意标签内容不变，原来什么样的还得是什么样，因为BasicCAT默认没有对标签做保护处理，容易出错。你可以发一些含有标签的翻译好的片段过来看看。

**Comment by xulihang** [comment]
我看了下，主要是`<bpt id="15" rid="15">`在译文中变成了`<bpt id="15"rid="15">`，缺少了中间的空格。标签可以没有，但一旦出错，导回就失败了。译文框的文本会自动换行，有时候看不出是不是缺少空格（这点在下一版本中会改善，可以用下划线表示空格）。建议翻译标签时，先使用CTRL+P，把原文复制到译文，然后修改需要翻译的部分，不要动`<>`包裹的内容。

**Comment by xulihang** [comment]
提交前可以用checkmate、xbench之类的翻译质量检查工具先检查看看。标签是否错误的检查在BasicCAT以后的版本会添加。
