### ISSUE TITLE
作者你好可以写一下日语和中文互相翻译的教程么？至少在你提到的这一步，谢谢！

### ISSUE THREAD

**Issue by xuemengmeng520** [xulihang/BasicCAT-docs#5]
输入基于ISO639标准的语言代码创建项目，并在“项目路径/配置”中的segmentation.conf中添加必要的规则。

**Comment by xuemengmeng520** [comment]
作者你好可以写一下日语和中文互相翻译的教程么？至少在你提到的这一步，谢谢！

**Comment by xulihang** [comment]
没什么特别的操作，选择语言对后直接用就行了
