### ISSUE TITLE
去字以后掩模的地方变黑了，没有被虚化？

### ISSUE THREAD

**Issue by haofan170** [xulihang/BasicCAT-docs#6]
就一张图片会这样。。没搞懂原因
![QQ截图20230511014921](https://github.com/xulihang/BasicCAT-docs/assets/49093867/bc875c1b-3797-4f26-b1f1-c8e8e8974709)

**Comment by xulihang** [comment]
发错地方了，请发在这里：https://github.com/xulihang/ImageTrans-docs/issues
